# Generated by Django 4.1.1 on 2022-10-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batchs',
            fields=[
                ('id_batch', models.AutoField(primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=45, unique=True)),
                ('size', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('number_electrical_ok', models.PositiveSmallIntegerField()),
                ('number_electrical_nok', models.PositiveSmallIntegerField()),
                ('number_functional_ok', models.PositiveSmallIntegerField()),
                ('number_functional_nok', models.PositiveSmallIntegerField()),
                ('batch_date_start', models.DateTimeField(blank=True, null=True)),
                ('batch_date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batchs',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('result', models.CharField(max_length=3)),
                ('value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id_manufacturer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.TextField()),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id_model', models.SmallAutoField(primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=40)),
                ('firmware', models.TextField()),
                ('bootloader', models.TextField()),
                ('xbee_firmware', models.TextField()),
                ('electrical_test', models.TextField()),
                ('functional_test', models.TextField()),
                ('valid_model', models.CharField(max_length=3)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=23, null=True)),
                ('electrical_result', models.CharField(blank=True, max_length=3, null=True)),
                ('electrical_date', models.DateTimeField(blank=True, null=True)),
                ('electrical_count', models.PositiveSmallIntegerField()),
                ('functional_result', models.CharField(blank=True, max_length=3, null=True)),
                ('functional_date', models.DateTimeField(blank=True, null=True)),
                ('functional_count', models.PositiveSmallIntegerField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.batchs')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.models')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Reworks',
            fields=[
                ('id_rework', models.SmallAutoField(primary_key=True, serialize=False)),
                ('designator', models.TextField()),
                ('operation', models.TextField()),
            ],
            options={
                'db_table': 'reworks',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id_test', models.SmallAutoField(primary_key=True, serialize=False)),
                ('test', models.TextField()),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestBenchs',
            fields=[
                ('id_test_bench', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('computer_serial_number', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_last_calibration', models.DateTimeField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.manufacturers')),
            ],
            options={
                'db_table': 'test_benchs',
            },
        ),
        migrations.CreateModel(
            name='SerialNumbers',
            fields=[
                ('id_serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField()),
                ('week', models.SmallIntegerField()),
                ('identifiant', models.PositiveSmallIntegerField()),
                ('affected', models.CharField(max_length=3)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.batchs')),
            ],
            options={
                'db_table': 'serial_numbers',
                'unique_together': {('id_serial_number', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='ProductsHasReworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_id', to='reworking.logs')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.products')),
                ('rework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.reworks')),
            ],
            options={
                'db_table': 'products_has_reworks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='serial_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.serialnumbers'),
        ),
        migrations.AddField(
            model_name='logs',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.products'),
        ),
        migrations.AddField(
            model_name='logs',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.tests'),
        ),
        migrations.AddField(
            model_name='logs',
            name='test_bench',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.testbenchs'),
        ),
        migrations.AddField(
            model_name='batchs',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.models'),
        ),
        migrations.AlterUniqueTogether(
            name='logs',
            unique_together={('id_log', 'test_bench', 'product', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='batchs',
            unique_together={('id_batch', 'model')},
        ),
    ]
