# Generated by Django 4.1.1 on 2022-10-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reworking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshasreworks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.products'),
        ),
    ]
