# Generated by Django 4.1.1 on 2022-10-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reworking', '0002_alter_productshasreworks_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshasreworks',
            name='log',
            field=models.ForeignKey(limit_choices_to=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reworking.products'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_id', to='reworking.logs'),
        ),
    ]
