# Generated by Django 4.1.1 on 2022-10-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reworking', '0003_alter_productshasreworks_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshasreworks',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_id', to='reworking.logs'),
        ),
    ]
